# Generated by Django 5.1 on 2024-09-03 00:51

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Campaign Unique ID.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Campaign Name.", max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the campaign was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the campaign was updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "role",
                    models.CharField(
                        choices=[("Trainer", "trainer"), ("Lead", "lead")],
                        help_text="Member Role.",
                        max_length=7,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Member email, also primary key.",
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Member full name.", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the member was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the member was updated.",
                    ),
                ),
                (
                    "campaign",
                    models.ManyToManyField(
                        help_text="Member's Campaign Foreign keys.",
                        related_name="members",
                        to="tms_manager.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in progress", "In Progress"),
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                        ],
                        help_text="Task's status.",
                        max_length=11,
                    ),
                ),
                ("name", models.CharField(help_text="Task's name.", max_length=255)),
                (
                    "score",
                    models.FloatField(
                        help_text="Task's continuous Score, can vary from 1.0 to 7.0.",
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(7.0),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the task was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the task was updated.",
                    ),
                ),
                (
                    "campaign",
                    models.ManyToManyField(
                        help_text="Member's Campaign Foreign keys.",
                        related_name="tasks",
                        to="tms_manager.campaign",
                    ),
                ),
                (
                    "lead",
                    models.ManyToManyField(
                        help_text="Member's (trainer) Campaign Foreign keys.",
                        limit_choices_to={"role": "Lead"},
                        related_name="reviewed_tasks",
                        to="tms_manager.member",
                    ),
                ),
                (
                    "trainer",
                    models.ManyToManyField(
                        help_text="Member's (trainer) Campaign Foreign keys.",
                        limit_choices_to={"role": "Trainer"},
                        related_name="tasks",
                        to="tms_manager.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["name"],
            },
        ),
    ]
